#!/bin/ksh

function cpng {
	djxl "$1" - --output_format png | gm convert - -profile /usr/local/share/color/icc/krita/sRGB-elle-V2-srgbtrc.icc -depth 8 "${1%jxl}png"
}

function cjpg {
	djxl "$1" - --output_format jpeg | gm convert - -profile /usr/local/share/color/icc/krita/sRGB-elle-V2-srgbtrc.icc -depth 8 "${1%jxl}jpg"
}

function cbeebies {
	fuck you
}

function ltx_internal {
        lualatex --draftmode "$1" &&
        bibtex "${1%.tex}";
        lualatex --draftmode "$1" &&
        lualatex "$1";

        # | ni'o xu cadga fa lo nu vimcu  .i ga je pilno
        # la'o zoi. ltx_internal .zoi. tu'a lo mulno noi
        # tu'a lo se vimcu cu na sarcu lo nu pilno ke'a
        for i in dvi log aux toc out bbl snm nav blg
        do
                rm "${1%.tex}.$i" &
        done;
}

function ltx {
	G="${1%.tex}.pdf";

	if test -e "$G"
	then
		if test "$(stat -f '%m' \"$G\")" -le "$(stat -f '%m' \"$1\")"
                then
			ltx_internal "$1";
		else
			echo "The file is aleady compiled, jack-ass.";
		fi
	else ltx_internal "$1";
	fi
}

cpng "deliriumsequels/deliriumsequels-kb.jxl"
cpng "blackholeblackhole/blackholeblackhole-sfw.jxl"
cpng "blackholeblackhole/blackholeblackhole-1v1x4-sfw.jxl"
cpng "blinddateatthewaxmuseum/blinddateatthewaxmuseum.jxl"
cpng "blinddateatthewaxmuseum/blinddateatthewaxmuseum-whisk.jxl"
cpng "blinddateatthewaxmuseum/ctinytsautur.jxl"
cpng "wedancealonethisway/wedancealonethisway.jxl"
cjpg "wedancealonethisway/sipygai0w1.jxl"
cpng "takingturnsbreakingwords/takingturnsbreakingwords-rc4.jxl"

ltx "drawings.tex"
