#!/bin/ksh

function cvxx {
	if [ "$1" = "jpg" ]
	then
		FMT="jpeg"
	elif [ "$1" = "png" ]
	then
		FMT="png"
	else
		echo "ni'o la'oi .cvxx. na mapti tu'a zoi .zoix. $1 .zoix."
		exit
	fi

	if [ -s "${2%jxl}$1" ]
	then
		echo "ni'o zasti"
	else
		djxl "$2" - --output_format $FMT | gm convert - -profile /usr/local/share/color/icc/krita/sRGB-elle-V2-srgbtrc.icc -depth 8 "${2%jxl}$1"
	fi
}

function ltx_internal {
        lualatex --draftmode "$1" &&
        bibtex "${1%.tex}";
        lualatex --draftmode "$1" &&
        lualatex "$1";

        # | ni'o xu cadga fa lo nu vimcu  .i ga je pilno
        # la'o zoi. ltx_internal .zoi. tu'a lo mulno noi
        # tu'a lo se vimcu cu na sarcu lo nu pilno ke'a
        for i in dvi log aux toc out bbl snm nav blg
        do
                rm "${1%.tex}.$i" &
        done;
}

function ltx {
	G="${1%.tex}.pdf";

	if test -e "$G"
	then
		if test "$(stat -f '%m' \"$G\")" -le "$(stat -f '%m' \"$1\")"
                then
			ltx_internal "$1";
		else
			echo ".i na li'armi mi fa lo du'u sarcu fa lo nu co'e ja rapli pe'a fa lo pu'u samrkompli"
		fi
	else ltx_internal "$1";
	fi
}

cvxx png "deliriumsequels/deliriumsequels-kb.jxl"
cvxx png "blackholeblackhole/blackholeblackhole-sfw.jxl"
cvxx png "blackholeblackhole/blackholeblackhole-1v1x4-sfw.jxl"
cvxx png "blinddateatthewaxmuseum/blinddateatthewaxmuseum.jxl"
cvxx png "blinddateatthewaxmuseum/blinddateatthewaxmuseum-whisk.jxl"
cvxx png "blinddateatthewaxmuseum/ctinytsautur.jxl"
cvxx png "wedancealonethisway/wedancealonethisway.jxl"
cvxx jpg "wedancealonethisway/sipygai0w1.jxl"
cvxx png "takingturnsbreakingwords/takingturnsbreakingwords-rc4.jxl"
cvxx png "shininglikecrystaltiaras/dvt1.jxl"
cvxx png "shininglikecrystaltiaras/dvt2.jxl"
cvxx png "itsastrangeinvitation/itsastrangeinvitation-rc2.jxl"
cvxx png "itsastrangeinvitation/ts1.jxl"
cvxx png "suchabeautifulway/rc3.jxl"
cvxx png "suchabeautifulway/rc3-flira.jxl"
cvxx png "suchabeautifulway/trashy-proof-of-concept.jxl"
cvxx png "suchabeautifulway/calsamxra-co-stedu-co-skari.jxl"
cvxx jpg "csx1/kerfa-1.jxl"
cvxx png "csx1/kerfa-2.jxl"
cvxx png "csx1/lmc-1.jxl"
cvxx png "almostaghost/rc4.jxl"

(export CMENE=shininglikecrystaltiaras && cd $CMENE && djxl $CMENE.jxl --output_format apng - | ffmpeg -y -f apng -i - -vf 'select=eq(2\,n)' -vframes 1 $CMENE-ctino2.png)
(cd suchabeautifulway && djxl rc3-flira.jxl --output_format apng - | ffmpeg -y -f apng -i - -vf 'select=eq(1\,n)' -vframes 1 rc3-flira.png)
(cd droningoutofatincan && djxl m.jxl --output_format apng - | ffmpeg -y -f apng -i - -vf 'select=eq(0\,n)' -vframes 1 rc4.png)
(cd droningoutofatincan && djxl m.jxl --output_format apng - | ffmpeg -y -f apng -i - -vf 'select=eq(1\,n)' -vframes 1 rc6.png)
(cd strangerstranger && djxl m.jxl --output_format apng - | ffmpeg -y -c:v png -i - -vframes 1 rc2.png)
(cd mwjbg && djxl m.jxl --output_format apng - | ffmpeg -y -c:v png -i - -vframes 1 rc3.png)
(cd dontburnmytoast && djxl m.jxl --output_format apng - | ffmpeg -y -c:v png -i - -vframes 1 m.png)
(cd droningoutofatincan && djxl m.jxl --output_format apng - | ffmpeg -y -f apng -i - -vf 'select=eq(0\,n)' -vframes 1 rc6.png)
(cd ty2bcdtd && djxl m.jxl --output_format apng - | ffmpeg -y -c:v apng -i - -vframes 1 m.png)

ltx "drawings.tex"

(/usr/local/bin/gs -dPDFSETTINGS=/prepress -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -sOutputFile=drawings-cmalu.pdf -dBATCH -dNOPAUSE drawings.pdf && rm drawings.pdf && mv drawings-cmalu.pdf drawings.pdf)
